name: Scheduled Job

on:
push:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
